"""Trading Signal Model"""

from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime
from typing import Optional, Dict, Any


class SignalType(Enum):
    """Trading signal direction"""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    EXIT = "exit"


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Includes confidence level and indicator reasoning.
    """
    
    strategy_name: str
    symbol: str
    signal_type: SignalType
    timestamp: datetime
    price: float
    confidence: float  # 0.0 to 1.0
    regime: str
    
    # Indicator values that generated the signal
    indicator_values: Dict[str, Any] = field(default_factory=dict)
    
    # Optional reasoning/explanation
    reason: Optional[str] = None
    
    # Note: Validation removed - trust strategy code produces valid signals
    
    @property
    def is_entry_signal(self) -> bool:
        """True if signal should initiate a position"""
        return self.signal_type in (SignalType.BUY, SignalType.SELL)
    
    @property
    def is_exit_signal(self) -> bool:
        """True if signal should close a position"""
        return self.signal_type in (SignalType.EXIT, SignalType.HOLD)
    
    def __str__(self) -> str:
        return (
            f"Signal({self.strategy_name.upper()}: "
            f"{self.signal_type.value.upper()} {self.symbol} @ {self.price:.2f} "
            f"(confidence: {self.confidence:.1%}), regime: {self.regime})"
        )
